FROM mcr.microsoft.com/dotnet/sdk:5.0 AS base
WORKDIR /app
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["WordSortingApp.csproj", ""]
RUN dotnet restore "./WordSortingApp.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "WordSortingApp.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "WordSortingApp.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WordSortingApp.dll"]